// lib/constants.ts
// Contract addresses, ABIs, RPC URLs, and test token addresses.

// ── Test Token Addresses ─────────────────────────────────────
// Documented for Day 1 verification and ongoing testing.

export const TEST_TOKENS = {
  /**
   * April 3rd exploit token — recipientAddress is a contract,
   * causing all sells to fail (honeypot). Should trigger Rule 1 CRITICAL.
   * Expected Risk Score: 0-29 (CRITICAL)
   */
  CRITICAL_HONEYPOT: '0xe9d11f369df3cece5c9fbcf6354123f58dafffff',

  /**
   * Safe token — 耄耋小精灵 (Old Sprite), completed bonding curve, listed on PancakeSwap.
   * Expected Risk Score: 70-100 (LOW-MEDIUM)
   * Found on Four.meme: https://four.meme/token/0x1cce9b33bec59194cf5c3a45f785f1f60a244444
   */
  SAFE_TOKEN: '0x1cce9b33bec59194cf5c3a45f785f1f60a244444',

  /**
   * Medium-risk token — 税收给作者 (DOGI), 1% tax to author, bonding curve at ~14%.
   * Expected Risk Score: 30-69 (MEDIUM-HIGH)
   * Found on Four.meme: https://four.meme/token/0xb8d5d82da44e7072e09bdd3c664422f3f320ffff
   */
  MEDIUM_RISK: '0xb8d5d82da44e7072e09bdd3c664422f3f320ffff',
} as const;

// ── WBNB Address ─────────────────────────────────────────────
export const WBNB_ADDRESS = '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c';

// WBNB on BSC Testnet
export const WBNB_TESTNET_ADDRESS = '0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd';

// ── Four.meme API ────────────────────────────────────────────
export const FOURMEME_API_BASE = 'https://four.meme/api';

// ── TaxToken ABI (Human-Readable, ethers.js v6) ─────────────
export const TAX_TOKEN_ABI = [
  // State variables (public getter auto-generated by Solidity)
  'function feeAccumulated() view returns (uint256)',
  'function minDispatch() view returns (uint256)',
  'function feeRate() view returns (uint256)',
  'function rateFounder() view returns (uint256)',
  'function rateHolder() view returns (uint256)',
  'function rateBurn() view returns (uint256)',
  'function rateLiquidity() view returns (uint256)',
  'function minShare() view returns (uint256)',
  'function totalShares() view returns (uint256)',
  'function founder() view returns (address)',
  'function recipientAddress() view returns (address)',
  'function recipientRate() view returns (uint256)',
  'function minSharing() view returns (uint256)',
  'function _mode() view returns (uint256)',

  // User info and claiming
  'function userInfo(address) view returns (uint256 share, uint256 rewardDebt, uint256 claimable, uint256 claimed)',
  'function claimableFee(address) view returns (uint256)',
  'function claimFee() external',
  'function claimedFee(address) view returns (uint256)',
];

// ── ERC20 Minimal ABI ────────────────────────────────────────
export const ERC20_ABI = [
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address) view returns (uint256)',
];

// ── BSC Chain IDs ────────────────────────────────────────────
export const BSC_MAINNET_CHAIN_ID = 56;
export const BSC_TESTNET_CHAIN_ID = 97;
